COREUTILS = \
	cat.c \
	echo.c \
	ed.c \
	ln.c \
	ls.c \
	mkdir.c \
	now.c \
	rm.c \
	sh.c \
	touch.c \
	wc.c

SERVERS = \
	audio.c \
	flash.c \
	fs.c \
	init.c \
	io.c \
	process.c \
	uart.c \
	usb.c

KERNEL = \
	boot.c \
	ipc.c \
	task.c
